### ISSUE TITLE
create_thread & NtCreateThreadEx_32_to_64

### ISSUE THREAD

**Issue by quentinhardy** [hakril/PythonForWindows#10] opened 2020-01-16 14:49 UTC
Hello,

I am using python 2.7 (X86 version) and the version 0.5 of PythonForWindows (on pip) on Windows 10.

When I try to use _create_thread()_ from **x86** process, more exactly _**NtCreateThreadEx_32_to_64()**_, for creating/executing a new thread on (another) **x64** process, I have a the following error:
```
[...]
  File ".\test.py", line 193, in testRemoteThread
    winProcess.create_thread(addr=reflectiveLoader, param=0)
  File "C:\Python27\lib\site-packages\pythonforwindows-0.5-py2.7.egg\windows\winobject\process.py", line 1040, in create_thread
    windows.syswow64.NtCreateThreadEx_32_to_64(ThreadHandle=byref(thread_handle) ,ProcessHandle=self.handle, lpStartAddress=addr, lpParameter=param)
  File "C:\Python27\lib\site-packages\pythonforwindows-0.5-py2.7.egg\windows\syswow64.py", line 260, in NtCreateThreadEx_32_to_64
    return NtCreateThreadEx_32_to_64.ctypes_function(ThreadHandle, DesiredAccess, ObjectAttributes, ProcessHandle, lpStartAddress, lpParameter, CreateSuspended, dwStackSize, Unknown1, Unknown2, Unknown3)
  File "C:\Python27\lib\site-packages\pythonforwindows-0.5-py2.7.egg\windows\syswow64.py", line 232, in perform_call
    return self.raw_call(*args)
  File "C:\Python27\lib\site-packages\pythonforwindows-0.5-py2.7.egg\windows\syswow64.py", line 138, in wrapper
    return native_caller()
WindowsError: exception: access violation writing 0x00000000
```
The targeted process is a _notepad.exe_ (x64) for example.
There is no one error before this function when I use _virtual_alloc()_, _write_memory()_ and _virtual_protect()_ for example.

Do you have an idea? There is a problem with _NtCreateThreadEx_32_to_64()_ from x86 process to x64 process?

Thank you in advance for your help,

Regards,

**Comment by hakril** [comment] 2020-01-18 20:19
Hello,

This is indeed problematic, `WinProcess.create_thread` should work to create a thread in a x64 process from a x86 one.
This is the role of `NtCreateThreadEx_32_to_64()` to create such thread and it should work, so I guess there is a problem. As I work, and test my code, mainly on Windows10 this behavior is really unexpected and I am quite interessted to find-out what is going one.

If you have time, could you do two things please.
First, try the following script (from a 32b python) that inject and execute a simple code in a 64b process and give me the output.
```python
import windows.test
import windows.native_exec.simple_x64 as x64

print("System: <{0}>".format(windows.system.version_name))
assert windows.current_process.bitness == 32
target = windows.test.pop_proc_64()
assert target.bitness == 64

code = x64.assemble("lea RAX, [RCX + 1]; ret")
addr = target.virtual_alloc(len(code))
target.write_memory(addr, code)

# Test1
try:
    t = target.create_thread(addr, 0)
    t.wait()
    print("Test1: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test1 Error: {0}".format(str(e)))

# Test2
try:
    t = target.create_thread(addr, 0x42424242)
    t.wait()
    print("Test2: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test2 Error: {0}".format(str(e)))
```

Also, if you could share a minimal script that trigger the bug on your side, that would help me test and find out its root.

Regards,

**Comment by quentinhardy** [comment] 2020-01-19 09:10
Hello,

Here is the output of the script:

```
System: <Windows 10>
('-------', [63114936, 2097151, 0, 872, 14614528, 0, 0, 0, 0, 0, 0])
Test1 Error: exception: access violation writing 0x00000000
('-------', [63114776, 2097151, 0, 872, 14614528, 1111638594, 0, 0, 0, 0, 0])
Test2 Error: exception: access violation writing 0x00000000
```
I do the same as you I think: OpenProcess(), VirtualAllocEx(), VirtualProtectEx() and NtCreateThreadEx_32_to_64().

Notice Windows Defender is disabled, just in case, and I use Windows 10 Pro (Build 18362.535, not the last version).

Thank you in advance for your help,

Regards,

**Comment by hakril** [comment] 2020-01-21 23:03
Well, my guess is that I do not pass a "mandatory" buffer that the function expect.
Based on research on internet, I would say that the faulty parameter is the last one.
The thing I do not understand is how all the versions I have tested so far have accepted the current set of parameters.

Anyway, here is another test that tries to figure the mandatory parameter and test it with a correctly setup buffer. Based on https://securityxploded.com/ntcreatethreadex.php & https://github.com/rasberryrabbit/Simple_units/blob/master/untcreatethreadex.pas.

```python
import ctypes
import struct
import windows.test
import windows.native_exec.simple_x64 as x64
import windows.generated_def as gdef

print("System: <{0}>".format(windows.system.version_name))
assert windows.current_process.bitness == 32
target = windows.test.pop_proc_64()
assert target.bitness == 64

code = x64.assemble("lea RAX, [RCX + 1]; ret")
addr = target.virtual_alloc(len(code))
target.write_memory(addr, code)

def do_NtCreateThreadEx_32_to_64(addr, param, Unknown1=0, Unknown2=0, Unknown3=0):
    res = gdef.HANDLE()
    windows.syswow64.NtCreateThreadEx_32_to_64(ctypes.addressof(res),
        ProcessHandle=target.handle,
        lpStartAddress=addr,
        lpParameter=param,
        Unknown1=Unknown1,
        Unknown2=Unknown2,
        Unknown3=Unknown3)
    t = windows.WinThread(handle=res.value)
    t.wait()
    return t

# From https://securityxploded.com/ntcreatethreadex.php
# https://github.com/rasberryrabbit/Simple_units/blob/master/untcreatethreadex.pas
class NtCreateThreadExBuffer64(ctypes.Structure):
    _fields_ = [
        ("Size", gdef.DWORD64),
        ("Unknown1", gdef.DWORD64),
        ("Unknown2", gdef.DWORD64),
        ("Unknown3", gdef.DWORD64),
        ("Unknown4", gdef.DWORD64),
        ("Unknown5", gdef.DWORD64),
        ("Unknown6", gdef.DWORD64),
        ("Unknown7", gdef.DWORD64),
        ("Unknown8", gdef.DWORD64),
    ]


# Test1
try:
    t = do_NtCreateThreadEx_32_to_64(addr, 1, Unknown1=0x41414141)
    print("Test1: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test1 Error: {0}".format(str(e)))

# Test2
try:
    t = do_NtCreateThreadEx_32_to_64(addr, 2, Unknown2=0x42424242)
    t.wait()
    print("Test2: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test2 Error: {0}".format(str(e)))


# Test3
try:
    t = do_NtCreateThreadEx_32_to_64(addr, 3, Unknown3=0x44444444)
    t.wait()
    print("Test3: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test3 Error: {0}".format(str(e)))

# Test4
try:
    buf = ctypes.c_buffer(0x1000)
    t = do_NtCreateThreadEx_32_to_64(addr, 4, Unknown3=buf)
    t.wait()
    print("Test4: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test4 Error: {0}".format(str(e)))


# Test5
try:
    tmp1 = gdef.DWORD64(0)
    tmp2 = gdef.DWORD64(0)
    ntbuf = NtCreateThreadExBuffer64()
    ntbuf.Size = ctypes.sizeof(NtCreateThreadExBuffer64)
    ntbuf.Unknown1 = 0x10003
    ntbuf.Unknown2 = 0x10
    ntbuf.Unknown3 = ctypes.addressof(tmp1)
    ntbuf.Unknown4 = 0
    ntbuf.Unknown5 = 0x10004
    ntbuf.Unknown6 = 8
    ntbuf.Unknown7 = ctypes.addressof(tmp2)
    ntbuf.Unknown8 = 0

    t = do_NtCreateThreadEx_32_to_64(addr, 5, Unknown3=ctypes.addressof(ntbuf))
    t.wait()
    print("Test5: {0:#x}".format(t.exit_code))
except WindowsError as e:
    print("Test5 Error: {0}".format(str(e)))
```
For information, the ouput on my computer (win10  build 18362.592) is :
```
System: <Windows 10>
Test1: 0x2
Test2: 0x3
Test3 Error: STATUS_ACCESS_VIOLATION(0xc0000005): The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
Test5: 0x6
```

**Comment by quentinhardy** [comment] 2020-01-25 10:00
Hello,

Sometimes, I have the following output (with Wind10 build 18362.535):
```
System: <Windows 10>
('-------', [58707640, 2097151, 0, 604, 3604480, 1, 0, 0, 1094795585, 0, 0])
Test1 Error: exception: access violation writing 0x00000000
('-------', [58707480, 2097151, 0, 604, 3604480, 2, 0, 0, 0, 1111638594, 0])
Test2 Error: exception: access violation writing 0x00000000
('-------', [58707720, 2097151, 0, 604, 3604480, 3, 0, 0, 0, 0, 1145324612])
Test3 Error: exception: access violation writing 0x00000000
('-------', [58707480, 2097151, 0, 604, 3604480, 4, 0, 0, 0, 0, 47478968])
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
('-------', [60403960, 2097151, 0, 604, 3604480, 5, 0, 0, 0, 0, 39634416])
Test5 Error: exception: access violation writing 0x00000000
```
Sometimes, I have no error in test 5:
```
System: <Windows 10>
('-------', [73060024, 2097151, 0, 868, 13369344, 1, 0, 0, 1094795585, 0, 0])
Test1 Error: exception: access violation writing 0x00000000
('-------', [73059864, 2097151, 0, 868, 13369344, 2, 0, 0, 0, 1111638594, 0])
Test2 Error: exception: access violation writing 0x00000000
('-------', [73060104, 2097151, 0, 868, 13369344, 3, 0, 0, 0, 0, 1145324612])
Test3 Error: exception: access violation writing 0x00000000
('-------', [73059864, 2097151, 0, 868, 13369344, 4, 0, 0, 0, 0, 61814936])
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
('-------', [74756344, 2097151, 0, 868, 13369344, 5, 0, 0, 0, 0, 53986640])
Test5: 0x6
```
or no error in test 2:
```
System: <Windows 10>
('-------', [71483064, 2097151, 0, 660, 10813440, 1, 0, 0, 1094795585, 0, 0])
Test1 Error: exception: access violation writing 0x00000000
('-------', [71482904, 2097151, 0, 660, 10813440, 2, 0, 0, 0, 1111638594, 0])
Test2: 0x3
('-------', [71482904, 2097151, 0, 660, 10813440, 3, 0, 0, 0, 0, 1145324612])
Test3 Error: exception: access violation writing 0x00000000
('-------', [71483064, 2097151, 0, 660, 10813440, 4, 0, 0, 0, 0, 60256432])
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
('-------', [73187576, 2097151, 0, 660, 10813440, 5, 0, 0, 0, 0, 52379688])
Test5 Error: exception: access violation writing 0x00000000
```
Notice I have no AV enabled.

**Comment by hakril** [comment] 2020-01-31 13:10
Thank you for the feedback, well this is definitively a bug somewhere on my side. I guess it is in the code generated by `syswow64.py`.
Unfortunately I am not able to reproduce de bug, so the debugging may require several round trips on this thread.

Could you try the last test script by replacing `windows/syswow64.py` with the version at https://gist.github.com/hakril/a8436c075b7b9099f50fc0f3c0db072d
This version just add assert that may help identify the root cause.

Thank you,

**Comment by hakril** [comment] 2020-01-31 16:04
Well, this is a BIG guess. but could you also give me your processor version ?
You can use the following PFW one-liner : 
`[c["Name"] for c in windows.system.wmi.select("Win32_Processor")]`

Thank you !

**Comment by quentinhardy** [comment] 2020-02-02 10:07
Hello,

The output with your modified syswow64.py file:

```
C:\Python27\python.exe .\test.py
USING DEBUG SYSWOW64.PY WITH ASSERT
System: <Windows 10>
Test1: 0x2
Test2 Error: exception: access violation writing 0x00000000
Test3 Error: exception: access violation writing 0x00000000
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
Test5 Error: exception: access violation writing 0x00000000
```
```
C:\Python27\python.exe .\test.py
USING DEBUG SYSWOW64.PY WITH ASSERT
System: <Windows 10>
Test1 Error: exception: access violation writing 0x00000000
Test2: 0x3
Test3 Error: exception: access violation writing 0x00000000
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
Test5 Error: exception: access violation writing 0x00000000
```
```
C:\Python27\python.exe .\test.py
USING DEBUG SYSWOW64.PY WITH ASSERT
System: <Windows 10>
Test1 Error: exception: access violation writing 0x00000000
Test2 Error: exception: access violation writing 0x00000000
Test3 Error: exception: access violation writing 0x00000000
Test4 Error: STATUS_INVALID_PARAMETER(0xc000000d): An invalid parameter was passed to a service or function
Test5 Error: exception: access violation writing 0x00000000
```

I'm using a Vmware virtual machine. 
My processor is an AMD Ryzen 7.

Regards,

**Comment by hakril** [comment] 2020-02-02 14:59
Thank you for all the information.
Based on your feedback, some friends and an AMD laptop I bought, I can tell you it is related to what seems to be a bug on the AMD CPUs :D

Can you try with the latest version of the gist at https://gist.github.com/hakril/a8436c075b7b9099f50fc0f3c0db072d ?
It seems to fix the bug on the AMD computer I tested.

If you are interested, it seems to be a bug related to the SS segment selector after a RETF instruction.
The fix is the ligne https://gist.github.com/hakril/a8436c075b7b9099f50fc0f3c0db072d#file-syswow64-py-L36 which reset the SS segment selector.

It looks like I am not the first one to discover that : http://blog.rewolf.pl/blog/?p=1484

**Comment by hakril** [comment] 2020-02-12 08:34
Hello.

@quentinhardy I would be interested by your feedback about the current fix (which is available in the `dev` branch)
This fix works on the AMD computers I tested on. But I would prefer having a confirmation from the issue creator before closing it.

Thank you,

**Comment by hakril** [comment] 2020-02-26 21:54
As I have no news about this bug since the fix linked to ARM processor. I am closing this Issue.
Feel free to reopen it if you stumble on this bug once again.

**Closed by hakril** 2020-02-26 21:54 UTC
