### ISSUE TITLE
An error occurred from python2 to python3

### ISSUE THREAD

**Issue by WBGlIl** [hakril/PythonForWindows#30] opened 2021-08-25 02:34 UTC
![image](https://user-images.githubusercontent.com/29301859/130717019-5d97320a-d0d9-4d91-9083-4200620c0eae.png)

  File "D:\Python39\lib\site-packages\windows\rpc\ndr.py", line 404, in pack
    packed_member = member.pack(memberdata)
  File "D:\Python39\lib\site-packages\windows\rpc\ndr.py", line 279, in pack
    return struct.pack("<I", 0) + str(bytearray(data))
TypeError: can't concat str to bytes
python-BaseException

**Comment by hakril** [comment] 2021-09-06 20:09
Hello,

Indeed it's a bug, the fix (and tests) are present in 134bd844.
Thank you for reporting it !
I am closing the issue, do not hesitate to reopen-it if you feel the issue is not fixed.
Do not hesitate to open other issues if you encounter bugs or have ideas about improvements.

**Closed by hakril** 2021-09-06 20:09 UTC
